AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  LeaderboardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HearthstoneLeaderboardV2
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: GameModeServerPlayer
          AttributeType: S
        - AttributeName: GameModeServer
          AttributeType: S
        - AttributeName: CurrentRank
          AttributeType: N
      KeySchema:
        - AttributeName: GameModeServerPlayer
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RankLookupIndex
          KeySchema:
            - AttributeName: GameModeServer
              KeyType: HASH
            - AttributeName: CurrentRank
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  LeaderboardUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dbUpdater.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeaderboardTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LeaderboardTable
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)

  UpdaterErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alert when updater function has errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LeaderboardUpdaterFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ErrorNotificationTopic

  ErrorNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: LeaderboardUpdaterErrors
